### ISSUE TITLE
Add descriptions to the existing newsletters list

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-newsletters#28]
We have a few newsletters but we could use some descriptions.
For each newsletter, please add a 1-2 sentence description.
Here is an example:

```md
## GENERAL

- [Accessibility Weekly](https://a11yweekly.com/)
  This is a weekly accessibility newsletter that is delivered to your inbox every Monday.
  <br>
```

Please read through the [contributing documentation](https://github.com/thisdot/tech-newsletters/blob/main/CONTRIBUTING.md) before making a pull request. 

**Please note: If you are interested in working on this, leave a comment on this issue and we will assign it to you.**

**Comment by ahmedsilat44** [comment]
Hey @jdwilkin4 I am new to Open Source and this is my first time taking part in hacktoberfest. I would really like to take on this task, If it is available could u assign it to me.

**Comment by jdwilkin4** [comment]
Hi @ahmedsilat44 ! 

This issue is still available for assignment. I do have to let you know that hactoberfest doesn't officially start until October though. All PR's have to be merged during the month of October. Any PR's merged before October won't count. 

I am happy to assign this to you because we are only a few days away from the start of the event. 
Just wanted to let you know about the hacktoberfest submission rules 👍

**Comment by ahmedsilat44** [comment]
@jdwilkin4 Thank you for the heads up. I will wait until October to make the PR.
