### ISSUE TITLE
[Request] Create a webpage on GitHub Pages.

### ISSUE THREAD

**Issue by ahmedsilat44** [thisdot/tech-newsletters#33]
Maybe a github page from the README.md file would be a cool addition to this repo.
What it would look like :
![image](https://user-images.githubusercontent.com/105588821/194014546-33759969-bbfd-4fb9-b335-3bde3c71aa87.png)
![image](https://user-images.githubusercontent.com/105588821/194014560-d103613b-adb9-42ae-92b9-d49a0ab68359.png)

**Comment by ahmedsilat44** [comment]
@jdwilkin4 if you want this feature you can assign me and I'd like to make this addition. Thanks 😄

**Comment by jdwilkin4** [comment]
HI @ahmedsilat44 ! 

Thank you for creating this issue! 
At this time, we are not looking to add on any new features.
