### ISSUE TITLE
Alphabetize lists and remove duplicates

### ISSUE THREAD

**Issue by jdwilkin4** [thisdot/tech-newsletters#39]
Some of the lists are out of order and need to be alphabetized again.
Please go through each of the categories, and sort them in alphabetical order.
If there are duplicate newsletters, please remove them after the list has been put in order. 

If you are interested in working on this issue, please comment below and it will be assigned to you.
If you are new to this repository, please read through the [contributing docs](https://github.com/thisdot/tech-newsletters/blob/main/CONTRIBUTING.md) first.

**Please note**: issues will be assigned on a first come basis. Please do not start work on this issue until it has been assigned to you.

**Comment by varsha-kss** [comment]
please assign this issue to me

**Comment by varsha-kss** [comment]
i have to edit alphabatize in the readme file right?

**Comment by jdwilkin4** [comment]
Yes. 
If you go through each category you will notice that some of the entries are out of order.

For example take a look at the [General category](https://github.com/thisdot/tech-newsletters#general) you will see that entries like the changelog come after entries like sidebar which is incorrect alphabetically ordering. 
The goal of this issue is properly order each category in A-Z order.
